version: "3.8"
services:
  cors:
    build: .
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - NODE_ENV=product
      - CORSANYWHERE_WHITELIST=https://example.com,http://example.com,http://example.com:8080
